-- ** Oracle DDL Script for WordWeb Platform (English Table Names & Korean Comments) **

-- 1. 기존 테이블 및 시퀀스 삭제

DROP TABLE "WORD_RELATION" CASCADE CONSTRAINTS;
DROP TABLE "CLUSTER_WORD" CASCADE CONSTRAINTS;
DROP TABLE "COMPLETED_WORD" CASCADE CONSTRAINTS;
DROP TABLE "FAVORITE_WORD" CASCADE CONSTRAINTS;
DROP TABLE "WRONG_ANSWER_LOG" CASCADE CONSTRAINTS;
DROP TABLE "STORY_WORD_LIST" CASCADE CONSTRAINTS;
DROP TABLE "WRONG_ANSWER_STORY" CASCADE CONSTRAINTS;
DROP TABLE "STUDY_LOG" CASCADE CONSTRAINTS;
DROP TABLE "WORD" CASCADE CONSTRAINTS;
DROP TABLE "USERS" CASCADE CONSTRAINTS;
DROP TABLE "REFRESH_TOKEN" CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_USER_ID;
DROP SEQUENCE SEQ_WORD_ID;
DROP SEQUENCE SEQ_FAVORITE_WORD_ID;
DROP SEQUENCE SEQ_COMPLETED_WORD_ID;
DROP SEQUENCE SEQ_WRONG_WORD_ID;
DROP SEQUENCE SEQ_STUDY_LOG_ID;
DROP SEQUENCE SEQ_STORY_ID;
DROP SEQUENCE SEQ_CLUSTER_ID;

-- 2. 시퀀스 생성 (자동 증가 PK 컬럼에 사용)

CREATE SEQUENCE SEQ_USER_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WORD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FAVORITE_WORD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMPLETED_WORD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WRONG_WORD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_STUDY_LOG_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_STORY_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLUSTER_ID START WITH 1 INCREMENT BY 1 NOCACHE;

-- 3. 테이블 생성 및 기본 제약 조건 설정

-- 3.1. USERS (유저) 테이블

CREATE TABLE "USERS" (
	USER_ID	NUMBER		NOT NULL, -- 유저 고유 ID
	USER_PW	VARCHAR2(255)		NOT NULL, -- 비밀번호
	NICKNAME	VARCHAR2(100)		NOT NULL UNIQUE, -- 닉네임
	USER_NAME	VARCHAR2(50)		NOT NULL, -- 유저이름
	USER_BIRTH	VARCHAR2(255)		NOT NULL, -- 유저생년월일
	EMAIL	VARCHAR2(255)		NOT NULL, -- 이메일 (아이디로 사용, 복합키 일부)
	PREFERENCE	VARCHAR2(255)		NULL, -- 선호분야
	GOAL	VARCHAR2(255)		NULL, -- 학습목표
	DAILY_WORD_GOAL	NUMBER(38)	DEFAULT 20	NULL, -- 하루 목표 단어수
	CREATED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL, -- 가입일
	UPDATED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL -- 업데이트일
);

ALTER TABLE "USERS" ADD CONSTRAINT PK_USERS PRIMARY KEY (USER_ID, EMAIL);

COMMENT ON TABLE "USERS" IS '유저 정보';
COMMENT ON COLUMN "USERS".USER_ID IS '유저 고유번호 (복합키 일부)';
COMMENT ON COLUMN "USERS".USER_PW IS '비밀번호';
COMMENT ON COLUMN "USERS".NICKNAME IS '닉네임 (고유)';
COMMENT ON COLUMN "USERS".USER_NAME IS '유저 이름';
COMMENT ON COLUMN "USERS".USER_BIRTH IS '유저 생년월일';
COMMENT ON COLUMN "USERS".EMAIL IS '이메일 (아이디로 사용, 복합키 일부)';
COMMENT ON COLUMN "USERS".PREFERENCE IS '선호 분야';
COMMENT ON COLUMN "USERS".GOAL IS '학습 목표';
COMMENT ON COLUMN "USERS".DAILY_WORD_GOAL IS '하루 목표 단어 수';
COMMENT ON COLUMN "USERS".CREATED_AT IS '가입일';
COMMENT ON COLUMN "USERS".UPDATED_AT IS '업데이트일';

-- 3.2. WORD (단어) 테이블

CREATE TABLE "WORD" (
	WORD_ID	NUMBER		NOT NULL, -- 단어 고유 ID
	WORD	VARCHAR2(100)		NOT NULL UNIQUE, -- 영어 단어
	MEANING	VARCHAR2(255)		NOT NULL, -- 뜻
	PART_OF_SPEECH	VARCHAR2(50)		NULL, -- 품사
	EXAMPLE_SENTENCE_EN	CLOB		NULL, -- 영어 예문
	EXAMPLE_SENTENCE_KO	CLOB		NULL, -- 한국어 예문
	CATEGORY	VARCHAR2(50)		NULL, -- 분야 (IT, Business, Fashion, Trade 등)
	"LEVEL"	NUMBER		NULL, -- 난이도 (1-6: A1-C2)
	EMBEDDING	CLOB		NULL, -- 단어 임베딩 벡터 (JSON 배열)
	CREATED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL -- 생성일
);

ALTER TABLE "WORD" ADD CONSTRAINT PK_WORD PRIMARY KEY (WORD_ID);

COMMENT ON TABLE "WORD" IS '단어 정보';
COMMENT ON COLUMN "WORD".WORD_ID IS '단어 고유 ID (PK)';
COMMENT ON COLUMN "WORD".WORD IS '영어 단어 (고유)';
COMMENT ON COLUMN "WORD".MEANING IS '뜻';
COMMENT ON COLUMN "WORD".PART_OF_SPEECH IS '품사';
COMMENT ON COLUMN "WORD".EXAMPLE_SENTENCE_EN IS '영어 예문';
COMMENT ON COLUMN "WORD".EXAMPLE_SENTENCE_KO IS '한국어 예문';
COMMENT ON COLUMN "WORD".CATEGORY IS '분야';
COMMENT ON COLUMN "WORD"."LEVEL" IS '난이도 (1=A1, 2=A2, 3=B1, 4=B2, 5=C1, 6=C2)';
COMMENT ON COLUMN "WORD".EMBEDDING IS '단어 임베딩 벡터 (JSON 배열 형태로 저장)';
COMMENT ON COLUMN "WORD".CREATED_AT IS '생성일';

-- 3.3. FAVORITE_WORD (단어 즐겨찾기) 테이블

CREATE TABLE "FAVORITE_WORD" (
	FAVORITE_WORD_ID	NUMBER		NOT NULL, -- 즐겨찾기단어고유번호
	WORD_ID	NUMBER		NOT NULL, -- 단어고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	CREATED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL -- 추가일
);

ALTER TABLE "FAVORITE_WORD" ADD CONSTRAINT PK_FAVORITE_WORD PRIMARY KEY (FAVORITE_WORD_ID);

COMMENT ON TABLE "FAVORITE_WORD" IS '단어 즐겨찾기 정보';
COMMENT ON COLUMN "FAVORITE_WORD".FAVORITE_WORD_ID IS '즐겨찾기 단어 고유번호 (PK)';
COMMENT ON COLUMN "FAVORITE_WORD".WORD_ID IS '단어 고유번호 (FK)';
COMMENT ON COLUMN "FAVORITE_WORD".USER_ID IS '유저 ID (FK)';
COMMENT ON COLUMN "FAVORITE_WORD".CREATED_AT IS '추가일';

-- 3.4. WRONG_ANSWER_LOG (오답 저장) 테이블

CREATE TABLE "WRONG_ANSWER_LOG" (
	WRONG_WORD_ID	NUMBER		NOT NULL, -- 오답기록 고유번호
	WORD_ID	NUMBER		NOT NULL, -- 단어고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	WRONG_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL, -- 오답발생일
	TAG	VARCHAR2(50)		NULL, -- 태그
	IS_USED_IN_STORY	CHAR(1)	DEFAULT 'N'	NULL -- 스토리 생성 사용 여부
);

ALTER TABLE "WRONG_ANSWER_LOG" ADD CONSTRAINT PK_WRONG_ANSWER_LOG PRIMARY KEY (WRONG_WORD_ID);

COMMENT ON TABLE "WRONG_ANSWER_LOG" IS '오답 기록 정보';
COMMENT ON COLUMN "WRONG_ANSWER_LOG".WRONG_WORD_ID IS '오답 기록 고유번호 (PK)';
COMMENT ON COLUMN "WRONG_ANSWER_LOG".WORD_ID IS '단어 고유번호 (FK)';
COMMENT ON COLUMN "WRONG_ANSWER_LOG".USER_ID IS '유저 ID (FK)';
COMMENT ON COLUMN "WRONG_ANSWER_LOG".WRONG_AT IS '오답 발생일';
COMMENT ON COLUMN "WRONG_ANSWER_LOG".TAG IS '태그';
COMMENT ON COLUMN "WRONG_ANSWER_LOG".IS_USED_IN_STORY IS '스토리 생성 사용 여부';

-- 3.5. STUDY_LOG (학습 기록) 테이블

CREATE TABLE "STUDY_LOG" (
	STUDY_LOG_ID	NUMBER		NOT NULL, -- 학습기록고유번호
	WORD_ID	NUMBER		NOT NULL, -- 단어고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	"STATUS"	VARCHAR2(20)		NOT NULL, -- 학습 상태(learned / pending 등)
	LAST_RESULT	VARCHAR2(10)		NULL, -- 채점 결과(correct / wrong )
	LAST_STUDY_AT	TIMESTAMP		NULL, -- 마지막 학습
	TOTAL_CORRECT	NUMBER	DEFAULT 0	NULL, -- 정답 횟수
	TOTAL_WRONG	NUMBER	DEFAULT 0	NULL -- 오답 횟수
);

ALTER TABLE "STUDY_LOG" ADD CONSTRAINT PK_STUDY_LOG PRIMARY KEY (STUDY_LOG_ID);

COMMENT ON TABLE "STUDY_LOG" IS '단어 학습 기록 정보';
COMMENT ON COLUMN "STUDY_LOG".STUDY_LOG_ID IS '학습 기록 고유번호 (PK)';
COMMENT ON COLUMN "STUDY_LOG".WORD_ID IS '단어 고유번호 (FK)';
COMMENT ON COLUMN "STUDY_LOG".USER_ID IS '유저 ID (FK)';
COMMENT ON COLUMN "STUDY_LOG"."STATUS" IS '학습 상태(learned / pending 등)';
COMMENT ON COLUMN "STUDY_LOG".LAST_RESULT IS '채점 결과(correct / wrong)';
COMMENT ON COLUMN "STUDY_LOG".LAST_STUDY_AT IS '마지막 학습';
COMMENT ON COLUMN "STUDY_LOG".TOTAL_CORRECT IS '정답 횟수';
COMMENT ON COLUMN "STUDY_LOG".TOTAL_WRONG IS '오답 횟수';

-- 3.5.1. COMPLETED_WORD (학습 완료 단어) 테이블

CREATE TABLE "COMPLETED_WORD" (
	COMPLETED_WORD_ID	NUMBER		NOT NULL, -- 학습완료단어고유번호
	WORD_ID	NUMBER		NOT NULL, -- 단어고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	COMPLETED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL -- 완료일
);

ALTER TABLE "COMPLETED_WORD" ADD CONSTRAINT PK_COMPLETED_WORD PRIMARY KEY (COMPLETED_WORD_ID);

COMMENT ON TABLE "COMPLETED_WORD" IS '학습 완료한 단어 정보';
COMMENT ON COLUMN "COMPLETED_WORD".COMPLETED_WORD_ID IS '학습 완료 단어 고유번호 (PK)';
COMMENT ON COLUMN "COMPLETED_WORD".WORD_ID IS '단어 고유번호 (FK)';
COMMENT ON COLUMN "COMPLETED_WORD".USER_ID IS '유저 ID (FK)';
COMMENT ON COLUMN "COMPLETED_WORD".COMPLETED_AT IS '학습 완료일';

-- 3.6. WRONG_ANSWER_STORY (오답 스토리) 테이블

CREATE TABLE "WRONG_ANSWER_STORY" (
	STORY_ID	NUMBER		NOT NULL, -- 스토리고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	TITLE	CLOB		NOT NULL, -- 스토리 제목
	STORY_EN	CLOB		NOT NULL, -- 영어 스토리
	STORY_KO	CLOB		NOT NULL, -- 한글 스토리
	CREATED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL -- 생성일
);

ALTER TABLE "WRONG_ANSWER_STORY" ADD CONSTRAINT PK_WRONG_ANSWER_STORY PRIMARY KEY (STORY_ID);

COMMENT ON TABLE "WRONG_ANSWER_STORY" IS '오답 스토리 정보';
COMMENT ON COLUMN "WRONG_ANSWER_STORY".STORY_ID IS '스토리 고유번호 (PK)';
COMMENT ON COLUMN "WRONG_ANSWER_STORY".USER_ID IS '유저 ID (FK)';
COMMENT ON COLUMN "WRONG_ANSWER_STORY".TITLE IS '스토리 제목';
COMMENT ON COLUMN "WRONG_ANSWER_STORY".STORY_EN IS '영어 스토리';
COMMENT ON COLUMN "WRONG_ANSWER_STORY".STORY_KO IS '한글 스토리';
COMMENT ON COLUMN "WRONG_ANSWER_STORY".CREATED_AT IS '생성일';

-- 3.7. STORY_WORD_LIST (오답 스토리 단어 목록) 테이블

CREATE TABLE "STORY_WORD_LIST" (
	STORY_ID	NUMBER		NOT NULL, -- 스토리고유번호
	WRONG_WORD_ID	NUMBER		NOT NULL -- 오답기록 고유번호
);

ALTER TABLE "STORY_WORD_LIST" ADD CONSTRAINT PK_STORY_WORD_LIST PRIMARY KEY (
	STORY_ID,
	WRONG_WORD_ID
);

COMMENT ON TABLE "STORY_WORD_LIST" IS '오답 스토리와 오답 기록 연결 정보';
COMMENT ON COLUMN "STORY_WORD_LIST".STORY_ID IS '스토리 고유번호 (FK)';
COMMENT ON COLUMN "STORY_WORD_LIST".WRONG_WORD_ID IS '오답 기록 고유번호 (FK)';

-- 3.8. CLUSTER_WORD (단어 관계) 테이블

CREATE TABLE "CLUSTER_WORD" (
	CLUSTER_ID	NUMBER		NOT NULL, -- 클러스터고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	RELATED_WORD_ID	NUMBER		NOT NULL, -- 연관단어고유번호
	CENTER_WORD_ID	NUMBER		NOT NULL, -- 중심단어고유번호
	SCORE	NUMBER		NULL, -- 연관 강도(옵션)
	RELATION_TYPE	VARCHAR2(20)		NOT NULL, -- synonym / antonym / related / collocation
	CREATED_AT	TIMESTAMP		NOT NULL -- 생성일
);

ALTER TABLE "CLUSTER_WORD" ADD CONSTRAINT PK_CLUSTER_WORD PRIMARY KEY (CLUSTER_ID);

COMMENT ON TABLE "CLUSTER_WORD" IS '단어 관계 정보';
COMMENT ON COLUMN "CLUSTER_WORD".CLUSTER_ID IS '클러스터 고유번호 (PK)';
COMMENT ON COLUMN "CLUSTER_WORD".USER_ID IS '유저 ID (FK)';
COMMENT ON COLUMN "CLUSTER_WORD".RELATED_WORD_ID IS '연관 단어 고유번호 (FK)';
COMMENT ON COLUMN "CLUSTER_WORD".CENTER_WORD_ID IS '중심 단어 고유번호 (FK)';
COMMENT ON COLUMN "CLUSTER_WORD".SCORE IS '연관 강도(옵션)';
COMMENT ON COLUMN "CLUSTER_WORD".RELATION_TYPE IS '관계 유형(동의어/반의어/관련어/연어)';
COMMENT ON COLUMN "CLUSTER_WORD".CREATED_AT IS '생성일';

-- 3.9. REFRESH_TOKEN 테이블

CREATE TABLE "REFRESH_TOKEN" (
	USER_EMAIL VARCHAR2(255) PRIMARY KEY,
	REFRESH_TOKEN VARCHAR2(500) NOT NULL
);

COMMENT ON TABLE "REFRESH_TOKEN" IS '리프레시 토큰 정보';
COMMENT ON COLUMN "REFRESH_TOKEN".USER_EMAIL IS '유저 이메일 (PK)';
COMMENT ON COLUMN "REFRESH_TOKEN".REFRESH_TOKEN IS '리프레시 토큰';

-- 4. 외래 키 (Foreign Key) 설정

-- FAVORITE_WORD FKs
ALTER TABLE "FAVORITE_WORD" ADD CONSTRAINT FK_FAV_WORD_WORD FOREIGN KEY (WORD_ID) REFERENCES "WORD" (WORD_ID);
ALTER TABLE "FAVORITE_WORD" ADD CONSTRAINT FK_FAV_WORD_USER FOREIGN KEY (USER_ID) REFERENCES "USERS" (USER_ID);

-- WRONG_ANSWER_LOG FKs
ALTER TABLE "WRONG_ANSWER_LOG" ADD CONSTRAINT FK_WRONG_LOG_WORD FOREIGN KEY (WORD_ID) REFERENCES "WORD" (WORD_ID);
ALTER TABLE "WRONG_ANSWER_LOG" ADD CONSTRAINT FK_WRONG_LOG_USER FOREIGN KEY (USER_ID) REFERENCES "USERS" (USER_ID);

-- STUDY_LOG FKs
ALTER TABLE "STUDY_LOG" ADD CONSTRAINT FK_STUDY_LOG_WORD FOREIGN KEY (WORD_ID) REFERENCES "WORD" (WORD_ID);
ALTER TABLE "STUDY_LOG" ADD CONSTRAINT FK_STUDY_LOG_USER FOREIGN KEY (USER_ID) REFERENCES "USERS" (USER_ID);

-- COMPLETED_WORD FKs
ALTER TABLE "COMPLETED_WORD" ADD CONSTRAINT FK_COMPLETED_WORD_USER FOREIGN KEY (USER_ID) REFERENCES "USERS" (USER_ID);
ALTER TABLE "COMPLETED_WORD" ADD CONSTRAINT FK_COMPLETED_WORD_WORD FOREIGN KEY (WORD_ID) REFERENCES "WORD" (WORD_ID);

-- WRONG_ANSWER_STORY FKs
ALTER TABLE "WRONG_ANSWER_STORY" ADD CONSTRAINT FK_STORY_USER FOREIGN KEY (USER_ID) REFERENCES "USERS" (USER_ID);

-- STORY_WORD_LIST FKs
ALTER TABLE "STORY_WORD_LIST" ADD CONSTRAINT FK_SWL_STORY FOREIGN KEY (STORY_ID) REFERENCES "WRONG_ANSWER_STORY" (STORY_ID);
ALTER TABLE "STORY_WORD_LIST" ADD CONSTRAINT FK_SWL_WRONG_LOG FOREIGN KEY (WRONG_WORD_ID) REFERENCES "WRONG_ANSWER_LOG" (WRONG_WORD_ID);

-- CLUSTER_WORD FKs
ALTER TABLE "CLUSTER_WORD" ADD CONSTRAINT FK_CLUSTER_WORD_USER FOREIGN KEY (USER_ID) REFERENCES "USERS" (USER_ID);
ALTER TABLE "CLUSTER_WORD" ADD CONSTRAINT FK_CLUSTER_WORD_RELATED FOREIGN KEY (RELATED_WORD_ID) REFERENCES "WORD" (WORD_ID);
ALTER TABLE "CLUSTER_WORD" ADD CONSTRAINT FK_CLUSTER_WORD_CENTER FOREIGN KEY (CENTER_WORD_ID) REFERENCES "WORD" (WORD_ID);

-- REFRESH_TOKEN FKs
ALTER TABLE "REFRESH_TOKEN" ADD CONSTRAINT FK_REFRESH_TOKEN_USER FOREIGN KEY (USER_EMAIL) REFERENCES "USERS" (EMAIL);

-- 5. 자동 증가(Auto-Increment) 처리를 위한 트리거 생성

-- 5.1. USERS.USER_ID
CREATE OR REPLACE TRIGGER TRG_USERS_ID
BEFORE INSERT ON "USERS"
FOR EACH ROW
BEGIN
  IF :NEW.USER_ID IS NULL THEN
    SELECT SEQ_USER_ID.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
  END IF;
END;
/

-- 5.2. WORD.WORD_ID (PK)
CREATE OR REPLACE TRIGGER TRG_WORD_ID
BEFORE INSERT ON "WORD"
FOR EACH ROW
BEGIN
  IF :NEW.WORD_ID IS NULL THEN
    SELECT SEQ_WORD_ID.NEXTVAL INTO :NEW.WORD_ID FROM DUAL;
  END IF;
END;
/

-- 5.3. FAVORITE_WORD.FAVORITE_WORD_ID (PK)
CREATE OR REPLACE TRIGGER TRG_FAVORITE_WORD_ID
BEFORE INSERT ON "FAVORITE_WORD"
FOR EACH ROW
BEGIN
  IF :NEW.FAVORITE_WORD_ID IS NULL THEN
    SELECT SEQ_FAVORITE_WORD_ID.NEXTVAL INTO :NEW.FAVORITE_WORD_ID FROM DUAL;
  END IF;
END;
/

-- 5.3.1. COMPLETED_WORD.COMPLETED_WORD_ID (PK)
CREATE OR REPLACE TRIGGER TRG_COMPLETED_WORD_ID
BEFORE INSERT ON "COMPLETED_WORD"
FOR EACH ROW
BEGIN
  IF :NEW.COMPLETED_WORD_ID IS NULL THEN
    SELECT SEQ_COMPLETED_WORD_ID.NEXTVAL INTO :NEW.COMPLETED_WORD_ID FROM DUAL;
  END IF;
END;
/

-- 5.4. WRONG_ANSWER_LOG.WRONG_WORD_ID (PK)
CREATE OR REPLACE TRIGGER TRG_WRONG_WORD_ID
BEFORE INSERT ON "WRONG_ANSWER_LOG"
FOR EACH ROW
BEGIN
  IF :NEW.WRONG_WORD_ID IS NULL THEN
    SELECT SEQ_WRONG_WORD_ID.NEXTVAL INTO :NEW.WRONG_WORD_ID FROM DUAL;
  END IF;
END;
/

-- 5.5. STUDY_LOG.STUDY_LOG_ID (PK)
CREATE OR REPLACE TRIGGER TRG_STUDY_LOG_ID
BEFORE INSERT ON "STUDY_LOG"
FOR EACH ROW
BEGIN
  IF :NEW.STUDY_LOG_ID IS NULL THEN
    SELECT SEQ_STUDY_LOG_ID.NEXTVAL INTO :NEW.STUDY_LOG_ID FROM DUAL;
  END IF;
END;
/

-- 5.6. WRONG_ANSWER_STORY.STORY_ID (PK)
CREATE OR REPLACE TRIGGER TRG_STORY_ID
BEFORE INSERT ON "WRONG_ANSWER_STORY"
FOR EACH ROW
BEGIN
  IF :NEW.STORY_ID IS NULL THEN
    SELECT SEQ_STORY_ID.NEXTVAL INTO :NEW.STORY_ID FROM DUAL;
  END IF;
END;
/

-- 5.7. CLUSTER_WORD.CLUSTER_ID (PK)
CREATE OR REPLACE TRIGGER TRG_CLUSTER_ID
BEFORE INSERT ON "CLUSTER_WORD"
FOR EACH ROW
BEGIN
  IF :NEW.CLUSTER_ID IS NULL THEN
    SELECT SEQ_CLUSTER_ID.NEXTVAL INTO :NEW.CLUSTER_ID FROM DUAL;
  END IF;
END;
/

COMMIT;