
-- 시퀀스 생성 (자동 증가 PK 컬럼에 사용)
CREATE SEQUENCE SEQ_USER_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WORD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FAVORITE_WORD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WRONG_WORD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_STUDY_LOG_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_STORY_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLUSTER_ID START WITH 1 INCREMENT BY 1 NOCACHE;


-- 3. 테이블 생성 및 기본 제약 조건 설정

-- 3.1. 유저 (USER) 테이블
CREATE TABLE "유저" (
	USER_ID	NUMBER		NOT NULL, -- 유저 고유 ID
	USER_PW	VARCHAR2(255)		NOT NULL, -- 비밀번호
	NICKNAME	VARCHAR2(100)		NOT NULL UNIQUE, -- 닉네임
	USER_NAME	VARCHAR2(50)		NOT NULL, -- 유저이름
	USER_BIRTH	VARCHAR2(255)		NOT NULL, -- 유저생년월일
	EMAIL	VARCHAR2(255)		NOT NULL UNIQUE, -- 이메일
	PREFERENCE	VARCHAR2(255)		NULL, -- 선호분야
	GOAL	VARCHAR2(255)		NULL, -- 학습목표
	DAILY_WORD_GOAL	NUMBER(38)	DEFAULT 20	NULL, -- 하루 목표 단어수
	CREATED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL, -- 가입일
	UPDATED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL -- 업데이트일
);
ALTER TABLE "유저" ADD CONSTRAINT PK_USER PRIMARY KEY (USER_ID);
COMMENT ON TABLE "유저" IS '유저 정보';
COMMENT ON COLUMN "유저".USER_ID IS '유저 고유번호 (PK)';
COMMENT ON COLUMN "유저".USER_PW IS '비밀번호';
COMMENT ON COLUMN "유저".NICKNAME IS '닉네임 (고유)';
COMMENT ON COLUMN "유저".USER_NAME IS '유저 이름';
COMMENT ON COLUMN "유저".USER_BIRTH IS '유저 생년월일';
COMMENT ON COLUMN "유저".EMAIL IS '이메일 (고유)';
COMMENT ON COLUMN "유저".PREFERENCE IS '선호 분야';
COMMENT ON COLUMN "유저".GOAL IS '학습 목표';
COMMENT ON COLUMN "유저".DAILY_WORD_GOAL IS '하루 목표 단어 수';
COMMENT ON COLUMN "유저".CREATED_AT IS '가입일';
COMMENT ON COLUMN "유저".UPDATED_AT IS '업데이트일';

-- 3.2. 단어 (WORD) 테이블
CREATE TABLE "단어" (
	WORD_ID	NUMBER		NOT NULL, -- 단어 고유 ID
	WORD	VARCHAR2(100)		NOT NULL UNIQUE, -- 영어 단어
	MEANING	VARCHAR2(255)		NOT NULL, -- 뜻
	PART_OF_SPEECH	VARCHAR2(50)		NULL, -- 품사
	EXAMPLE_SENTENCE	CLOB		NULL, -- 예문
	CATEGORY	VARCHAR2(50)		NULL, -- 분야 (IT, Business, Fashion, Trade 등)
	"LEVEL"	VARCHAR2(20)		NULL, -- 난이도
	CREATED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL -- 생성일
);
ALTER TABLE "단어" ADD CONSTRAINT PK_WORD PRIMARY KEY (WORD_ID);
COMMENT ON TABLE "단어" IS '단어 정보';
COMMENT ON COLUMN "단어".WORD_ID IS '단어 고유 ID (PK)';
COMMENT ON COLUMN "단어".WORD IS '영어 단어 (고유)';
COMMENT ON COLUMN "단어".MEANING IS '뜻';
COMMENT ON COLUMN "단어".PART_OF_SPEECH IS '품사';
COMMENT ON COLUMN "단어".EXAMPLE_SENTENCE IS '예문';
COMMENT ON COLUMN "단어".CATEGORY IS '분야';
COMMENT ON COLUMN "단어"."LEVEL" IS '난이도';
COMMENT ON COLUMN "단어".CREATED_AT IS '생성일';

-- 3.3. 단어 즐겨찾기 (FAVORITE_WORD) 테이블
CREATE TABLE "단어 즐겨찾기" (
	FAVORITE_WORD_ID	NUMBER		NOT NULL, -- 즐겨찾기단어고유번호
	WORD_ID	NUMBER		NOT NULL, -- 단어고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	CREATED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL -- 추가일
);
ALTER TABLE "단어 즐겨찾기" ADD CONSTRAINT PK_FAVORITE_WORD PRIMARY KEY (FAVORITE_WORD_ID);
COMMENT ON TABLE "단어 즐겨찾기" IS '단어 즐겨찾기';
COMMENT ON COLUMN "단어 즐겨찾기".FAVORITE_WORD_ID IS '즐겨찾기 단어 고유번호 (PK)';
COMMENT ON COLUMN "단어 즐겨찾기".WORD_ID IS '단어 고유번호 (FK)';
COMMENT ON COLUMN "단어 즐겨찾기".USER_ID IS '유저 ID (FK)';
COMMENT ON COLUMN "단어 즐겨찾기".CREATED_AT IS '추가일';


-- 3.4. 오답 저장 (WRONG_WORD) 테이블
CREATE TABLE "오답 저장" (
	WRONG_WORD_ID	NUMBER		NOT NULL, -- 오답기록 고유번호
	WORD_ID	NUMBER		NOT NULL, -- 단어고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	WRONG_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL, -- 오답발생일
	TAG	VARCHAR2(50)		NULL, -- 태그
	IS_USED_IN_STORY	CHAR(1)	DEFAULT 'N'	NULL -- 스토리 생성 사용 여부
);
ALTER TABLE "오답 저장" ADD CONSTRAINT PK_WRONG_WORD PRIMARY KEY (WRONG_WORD_ID);
COMMENT ON TABLE "오답 저장" IS '오답 기록';
COMMENT ON COLUMN "오답 저장".WRONG_WORD_ID IS '오답 기록 고유번호 (PK)';
COMMENT ON COLUMN "오답 저장".WORD_ID IS '단어 고유번호 (FK)';
COMMENT ON COLUMN "오답 저장".USER_ID IS '유저 ID (FK)';
COMMENT ON COLUMN "오답 저장".WRONG_AT IS '오답 발생일';
COMMENT ON COLUMN "오답 저장".TAG IS '태그';
COMMENT ON COLUMN "오답 저장".IS_USED_IN_STORY IS '스토리 생성 사용 여부';

-- 3.5. 학습 기록 (STUDY_LOG) 테이블
CREATE TABLE "학습 기록" (
	STUDY_LOG_ID	NUMBER		NOT NULL, -- 학습기록고유번호
	WORD_ID	NUMBER		NOT NULL, -- 단어고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	"STATUS"	VARCHAR2(20)		NOT NULL, -- 학습 상태(learned / pending 등)
	LAST_RESULT	VARCHAR2(10)		NULL, -- 채점 결과(correct / wrong )
	LAST_STUDY_AT	TIMESTAMP		NULL, -- 마지막 학습
	TOTAL_CORRECT	NUMBER	DEFAULT 0	NULL, -- 정답 횟수
	TOTAL_WRONG	NUMBER	DEFAULT 0	NULL -- 오답 횟수
);
ALTER TABLE "학습 기록" ADD CONSTRAINT PK_STUDY_LOG PRIMARY KEY (STUDY_LOG_ID);
COMMENT ON TABLE "학습 기록" IS '단어 학습 기록';
COMMENT ON COLUMN "학습 기록".STUDY_LOG_ID IS '학습 기록 고유번호 (PK)';
COMMENT ON COLUMN "학습 기록".WORD_ID IS '단어 고유번호 (FK)';
COMMENT ON COLUMN "학습 기록".USER_ID IS '유저 ID (FK)';
COMMENT ON COLUMN "학습 기록"."STATUS" IS '학습 상태(learned / pending 등)';
COMMENT ON COLUMN "학습 기록".LAST_RESULT IS '채점 결과(correct / wrong)';
COMMENT ON COLUMN "학습 기록".LAST_STUDY_AT IS '마지막 학습';
COMMENT ON COLUMN "학습 기록".TOTAL_CORRECT IS '정답 횟수';
COMMENT ON COLUMN "학습 기록".TOTAL_WRONG IS '오답 횟수';

-- 3.6. 오답 스토리 (STORY) 테이블
CREATE TABLE "오답 스토리" (
	STORY_ID	NUMBER		NOT NULL, -- 스토리고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	TITLE	CLOB		NOT NULL, -- 스토리 제목
	STORY_EN	CLOB		NOT NULL, -- 영어 스토리
	STORY_KO	CLOB		NOT NULL, -- 한글 스토리
	CREATED_AT	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL -- 생성일
);
ALTER TABLE "오답 스토리" ADD CONSTRAINT PK_STORY PRIMARY KEY (STORY_ID);
COMMENT ON TABLE "오답 스토리" IS '오답 스토리';
COMMENT ON COLUMN "오답 스토리".STORY_ID IS '스토리 고유번호 (PK)';
COMMENT ON COLUMN "오답 스토리".USER_ID IS '유저 ID (FK)';
COMMENT ON COLUMN "오답 스토리".TITLE IS '스토리 제목';
COMMENT ON COLUMN "오답 스토리".STORY_EN IS '영어 스토리';
COMMENT ON COLUMN "오답 스토리".STORY_KO IS '한글 스토리';
COMMENT ON COLUMN "오답 스토리".CREATED_AT IS '생성일';

-- 3.7. 오답 스토리 단어 목록 (STORY_WRONG_WORD) 테이블
CREATE TABLE "오답 스토리 단어 목록" (
	STORY_ID	NUMBER		NOT NULL, -- 스토리고유번호
	WRONG_WORD_ID	NUMBER		NOT NULL -- 오답기록 고유번호
);
ALTER TABLE "오답 스토리 단어 목록" ADD CONSTRAINT PK_STORY_WRONG_WORD PRIMARY KEY (
	STORY_ID,
	WRONG_WORD_ID
);
COMMENT ON TABLE "오답 스토리 단어 목록" IS '오답 스토리-오답 기록 연결';
COMMENT ON COLUMN "오답 스토리 단어 목록".STORY_ID IS '스토리 고유번호 (FK)';
COMMENT ON COLUMN "오답 스토리 단어 목록".WRONG_WORD_ID IS '오답 기록 고유번호 (FK)';

-- 3.8. 단어 관계 (CLUSTER_WORD) 테이블
CREATE TABLE "단어 관계" (
	CLUSTER_ID	NUMBER		NOT NULL, -- 클러스터고유번호
	USER_ID	NUMBER		NOT NULL, -- 유저ID
	RELATED_WORD_ID	NUMBER		NOT NULL, -- 연관단어고유번호
	CENTER_WORD_ID	NUMBER		NOT NULL, -- 중심단어고유번호
	SCORE	NUMBER		NULL, -- 연관 강도(옵션)
	RELATION_TYPE	VARCHAR2(20)		NOT NULL, -- synonym / antonym / related / collocation
	CREATED_AT	TIMESTAMP		NOT NULL -- 생성일
);
ALTER TABLE "단어 관계" ADD CONSTRAINT PK_CLUSTER_WORD PRIMARY KEY (CLUSTER_ID);
COMMENT ON TABLE "단어 관계" IS '단어 관계 정보';
COMMENT ON COLUMN "단어 관계".CLUSTER_ID IS '클러스터 고유번호 (PK, Unique in Excel)';
COMMENT ON COLUMN "단어 관계".USER_ID IS '유저 ID (FK, Unique in Excel)';
COMMENT ON COLUMN "단어 관계".RELATED_WORD_ID IS '연관 단어 고유번호 (FK, Unique in Excel)';
COMMENT ON COLUMN "단어 관계".CENTER_WORD_ID IS '중심 단어 고유번호 (FK, Unique in Excel)';
COMMENT ON COLUMN "단어 관계".SCORE IS '연관 강도(옵션)';
COMMENT ON COLUMN "단어 관계".RELATION_TYPE IS '관계 유형';
COMMENT ON COLUMN "단어 관계".CREATED_AT IS '생성일';


-- 4. 외래 키 (Foreign Key) 설정

-- 단어 즐겨찾기 FKs
ALTER TABLE "단어 즐겨찾기" ADD CONSTRAINT FK_FAV_WORD_WORD FOREIGN KEY (WORD_ID) REFERENCES "단어" (WORD_ID);
ALTER TABLE "단어 즐겨찾기" ADD CONSTRAINT FK_FAV_WORD_USER FOREIGN KEY (USER_ID) REFERENCES "유저" (USER_ID);

-- 오답 저장 FKs
ALTER TABLE "오답 저장" ADD CONSTRAINT FK_WRONG_WORD_WORD FOREIGN KEY (WORD_ID) REFERENCES "단어" (WORD_ID);
ALTER TABLE "오답 저장" ADD CONSTRAINT FK_WRONG_WORD_USER FOREIGN KEY (USER_ID) REFERENCES "유저" (USER_ID);

-- 학습 기록 FKs
ALTER TABLE "학습 기록" ADD CONSTRAINT FK_STUDY_LOG_WORD FOREIGN KEY (WORD_ID) REFERENCES "단어" (WORD_ID);
ALTER TABLE "학습 기록" ADD CONSTRAINT FK_STUDY_LOG_USER FOREIGN KEY (USER_ID) REFERENCES "유저" (USER_ID);

-- 오답 스토리 FKs
ALTER TABLE "오답 스토리" ADD CONSTRAINT FK_STORY_USER FOREIGN KEY (USER_ID) REFERENCES "유저" (USER_ID);

-- 오답 스토리 단어 목록 FKs
ALTER TABLE "오답 스토리 단어 목록" ADD CONSTRAINT FK_SWW_STORY FOREIGN KEY (STORY_ID) REFERENCES "오답 스토리" (STORY_ID);
ALTER TABLE "오답 스토리 단어 목록" ADD CONSTRAINT FK_SWW_WRONG_WORD FOREIGN KEY (WRONG_WORD_ID) REFERENCES "오답 저장" (WRONG_WORD_ID);

-- 단어 관계 FKs
ALTER TABLE "단어 관계" ADD CONSTRAINT FK_CLUSTER_USER FOREIGN KEY (USER_ID) REFERENCES "유저" (USER_ID);
ALTER TABLE "단어 관계" ADD CONSTRAINT FK_CLUSTER_RELATED_WORD FOREIGN KEY (RELATED_WORD_ID) REFERENCES "단어" (WORD_ID);
ALTER TABLE "단어 관계" ADD CONSTRAINT FK_CLUSTER_CENTER_WORD FOREIGN KEY (CENTER_WORD_ID) REFERENCES "단어" (WORD_ID);


-- 5. 자동 증가(Auto-Increment) 처리를 위한 트리거 생성

-- 5.1. 유저.USER_ID
CREATE OR REPLACE TRIGGER TRG_USER_ID
BEFORE INSERT ON "유저"
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT SEQ_USER_ID.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;
END;
/

-- 5.2. 단어.WORD_ID (PK)
CREATE OR REPLACE TRIGGER TRG_WORD_ID
BEFORE INSERT ON "단어"
FOR EACH ROW
BEGIN
    IF :NEW.WORD_ID IS NULL THEN
        SELECT SEQ_WORD_ID.NEXTVAL INTO :NEW.WORD_ID FROM DUAL;
    END IF;
END;
/
-- 5.3. 단어 즐겨찾기.FAVORITE_WORD_ID (PK)
CREATE OR REPLACE TRIGGER TRG_FAVORITE_WORD_ID
BEFORE INSERT ON "단어 즐겨찾기"
FOR EACH ROW
BEGIN
    IF :NEW.FAVORITE_WORD_ID IS NULL THEN
        SELECT SEQ_FAVORITE_WORD_ID.NEXTVAL INTO :NEW.FAVORITE_WORD_ID FROM DUAL;
    END IF;
END;
/

-- 5.4. 오답 저장.WRONG_WORD_ID (PK)
CREATE OR REPLACE TRIGGER TRG_WRONG_WORD_ID
BEFORE INSERT ON "오답 저장"
FOR EACH ROW
BEGIN
    IF :NEW.WRONG_WORD_ID IS NULL THEN
        SELECT SEQ_WRONG_WORD_ID.NEXTVAL INTO :NEW.WRONG_WORD_ID FROM DUAL;
    END IF;
END;
/

-- 5.5. 학습 기록.STUDY_LOG_ID (PK)
CREATE OR REPLACE TRIGGER TRG_STUDY_LOG_ID
BEFORE INSERT ON "학습 기록"
FOR EACH ROW
BEGIN
    IF :NEW.STUDY_LOG_ID IS NULL THEN
        SELECT SEQ_STUDY_LOG_ID.NEXTVAL INTO :NEW.STUDY_LOG_ID FROM DUAL;
    END IF;
END;
/

-- 5.6. 오답 스토리.STORY_ID (PK)
CREATE OR REPLACE TRIGGER TRG_STORY_ID
BEFORE INSERT ON "오답 스토리"
FOR EACH ROW
BEGIN
    IF :NEW.STORY_ID IS NULL THEN
        SELECT SEQ_STORY_ID.NEXTVAL INTO :NEW.STORY_ID FROM DUAL;
    END IF;
END;
/

-- 5.7. 단어 관계.CLUSTER_ID (PK)
CREATE OR REPLACE TRIGGER TRG_CLUSTER_ID
BEFORE INSERT ON "단어 관계"
FOR EACH ROW
BEGIN
    IF :NEW.CLUSTER_ID IS NULL THEN
        SELECT SEQ_CLUSTER_ID.NEXTVAL INTO :NEW.CLUSTER_ID FROM DUAL;
    END IF;
END;
/

COMMIT;