CREATE TABLE "단어 관계" (
	"클러스터고유번호"	NUMBER		NOT NULL,
	"중심단어고유번호"	NUMBER	DEFAULT SEQ+TRG	NOT NULL,
	"연관단어고유번호"	NUMBER		NOT NULL,
	"연관 강도(옵션)"	NUMBER		NULL,
	"synonym / antonym / related / collocation"	VARCHAR2(20)		NOT NULL,
	"생성일"	TIMESTAMP		NOT NULL
);

CREATE TABLE "오답 스토리" (
	"스토리고유번호"	NUMBER		NOT NULL,
	"오답기록 고유번호"	NUMBER		NOT NULL,
	"유저ID"	NUMBER	DEFAULT SEQ+TRG	NOT NULL,
	"스토리 제목"	CLOB		NOT NULL,
	"영어 스토리"	CLOB		NOT NULL,
	"한글 스토리"	CLOB		NOT NULL,
	"사용된 단어 ID 목록 JSON (예: [101, 102])"	CJOB		NOT NULL,
	"생성일"	TIMESTAMP	DEFAULT DEFAULT SYSTIMESTAMP	NOT NULL
);

CREATE TABLE "오답 저장" (
	"오답기록 고유번호"	NUMBER		NOT NULL,
	"단어고유번호"	NUMBER		NOT NULL,
	"유저ID"	NUMBER	DEFAULT SEQ+TRG	NOT NULL,
	"오답발생일"	TIMESTAMP	DEFAULT DEFAULT SYSTIMESTAMP	NOT NULL,
	"태그"	VARCHAR2(50)		NULL,
	"스토리 생성 사용 여부"	CHAR(1)	DEFAULT DEFAULT 'N'	NULL
);

CREATE TABLE "단어" (
	"단어고유번호"	NUMBER		NOT NULL,
	"영어 단어"	VARCHAR2(100)	DEFAULT UNIQUE	NOT NULL,
	"뜻"	VARCHAR2(255)		NOT NULL,
	"품사"	VARCHAR2(50)		NULL,
	"예문"	CLOB		NULL,
	"분야 (IT, Business, Fashion, Trade 등)"	VARCHAR2(50)		NULL,
	"난이도"	VARCHAR2(20)		NULL,
	"생성일"	TIMESTAMP	DEFAULT DEFAULT SYSTIMESTAMP	NOT NULL
);

CREATE TABLE "단어 즐겨찾기" (
	"즐겨찾기단어고유번호"	NUMBER		NOT NULL,
	"단어고유번호"	NUMBER		NOT NULL,
	"유저ID"	NUMBER	DEFAULT SEQ+TRG	NOT NULL,
	"추가일"	TIMESTAMP	DEFAULT DEFAULT SYSTIMESTAMP	NOT NULL
);

CREATE TABLE "유저" (
	"유저ID"	NUMBER	DEFAULT SEQ+TRG	NOT NULL,
	"비밀번호"	VARCHAR(255)		NOT NULL,
	"닉네임"	VARCHAR(100)		NOT NULL,
	"유저이름"	VARCHAR(50)		NOT NULL,
	"유저생년월일"	VARCHAR(255)		NOT NULL,
	"이메일"	VARCHAR(255)	DEFAULT UNIQUE	NOT NULL,
	"선호분야"	VARCHAR(255)		NULL,
	"학습목표"	VARCHAR2(255)		NULL,
	"하루 목표 단어수"	INT	DEFAULT DEFAULT 20	NULL,
	"가입일"	TIMESTAMP	DEFAULT DEFAULT SYSTIMESTAMP	NOT NULL,
	"업데이트일"	TIMESTAMP	DEFAULT DEFAULT SYSTIMESTAMP	NOT NULL
);

CREATE TABLE "학습 기록" (
	"학습기록고유번호"	NUMBER	DEFAULT SEQ+TRG	NOT NULL,
	"단어고유번호"	NUMBER		NOT NULL,
	"유저ID"	NUMBER	DEFAULT SEQ+TRG	NOT NULL,
	"학습 상태(learned / pending 등)"	VARCHAR2(20)		NOT NULL,
	"채점 결과(correct / wrong )"	VARCHAR2(10)		NULL,
	"마지막 학습"	TIMESTAMP		NULL,
	"정답 횟수"	NUMBER	DEFAULT DEFAULT 0	NULL,
	"오답 횟수"	NUMBER	DEFAULT DEFAULT 0	NULL
);

ALTER TABLE "단어 관계" ADD CONSTRAINT "PK_단어 관계" PRIMARY KEY (
	"클러스터고유번호"
);

ALTER TABLE "오답 스토리" ADD CONSTRAINT "PK_오답 스토리" PRIMARY KEY (
	"스토리고유번호"
);

ALTER TABLE "오답 저장" ADD CONSTRAINT "PK_오답 저장" PRIMARY KEY (
	"오답기록 고유번호"
);

ALTER TABLE "단어" ADD CONSTRAINT "PK_단어" PRIMARY KEY (
	"단어고유번호"
);

ALTER TABLE "단어 즐겨찾기" ADD CONSTRAINT "PK_단어 즐겨찾기" PRIMARY KEY (
	"즐겨찾기단어고유번호"
);

ALTER TABLE "유저" ADD CONSTRAINT "PK_유저" PRIMARY KEY (
	"유저ID"
);

ALTER TABLE "학습 기록" ADD CONSTRAINT "PK_학습 기록" PRIMARY KEY (
	"학습기록고유번호"
);

